import { describe, it, expect } from "vitest";
import actionsJson from "../../server/assets/preset_actions.json?raw";
import monstersJson from "../../server/assets/preset_monsters.json?raw";
import { ALL_PRESET_ACTIONS } from "../presets/actions";
import { PRESET_MONSTERS } from "../presets/bestiary";

/**
 * Drift guard for the server's embedded content. The Rust binary ships
 * `server/assets/preset_*.json` (generated by scripts/export_presets.ts);
 * these tests fail if the TS library changes without re-exporting.
 */
describe("Server preset export freshness", () => {
  it("preset_actions.json matches the current TS action registry", () => {
    const exported = JSON.parse(actionsJson);
    expect(exported).toEqual(ALL_PRESET_ACTIONS);
  });

  it("preset_monsters.json matches the current TS bestiary", () => {
    const exported = JSON.parse(monstersJson);
    const expected = PRESET_MONSTERS.map((m) => ({ ...m, id: `preset_${m.key}` }));
    expect(exported).toEqual(expected);
  });
});
