/**
 * Equipment catalog for quick inventory stocking. Purely descriptive —
 * weight autofills new inventory items; tags hint at future mechanics.
 */
export interface EquipmentEntry {
  name: string;
  category: "weapon" | "armor" | "gear" | "tool" | "potion" | "magic";
  weight: number;
  /** Typical quantity when added. */
  qty?: number;
  notes?: string;
  tags?: string[];
}

export const EQUIPMENT_CATALOG: EquipmentEntry[] = [
  // ── Weapons ────────────────────────────────────────────────────────────
  { name: "Dagger", category: "weapon", weight: 1, notes: "1d4 piercing, finesse, thrown 20/60" },
  { name: "Shortsword", category: "weapon", weight: 2, notes: "1d6 piercing, finesse" },
  { name: "Rapier", category: "weapon", weight: 2, notes: "1d8 piercing, finesse" },
  { name: "Scimitar", category: "weapon", weight: 3, notes: "1d6 slashing, finesse" },
  { name: "Longsword", category: "weapon", weight: 3, notes: "1d8 slashing (1d10 two-handed)" },
  { name: "Battleaxe", category: "weapon", weight: 4, notes: "1d8 slashing (1d10 two-handed)" },
  { name: "Greataxe", category: "weapon", weight: 7, notes: "1d12 slashing, heavy" },
  { name: "Greatsword", category: "weapon", weight: 6, notes: "2d6 slashing, heavy" },
  { name: "Warhammer", category: "weapon", weight: 3, notes: "1d8 bludgeoning (1d10 two-handed)" },
  { name: "Mace", category: "weapon", weight: 4, notes: "1d6 bludgeoning" },
  { name: "Club", category: "weapon", weight: 2, notes: "1d4 bludgeoning" },
  { name: "Morningstar", category: "weapon", weight: 4, notes: "1d8 piercing" },
  { name: "Spear", category: "weapon", weight: 3, qty: 1, notes: "1d6 piercing, thrown 20/60" },
  { name: "Halberd", category: "weapon", weight: 6, notes: "1d10 slashing, reach" },
  { name: "Whip", category: "weapon", weight: 3, notes: "1d4 slashing, finesse, reach" },
  { name: "Quarterstaff", category: "weapon", weight: 4, notes: "1d6 bludgeoning" },
  { name: "Handaxe", category: "weapon", weight: 2, qty: 1, notes: "1d4 slashing, thrown 20/60" },
  { name: "Javelin", category: "weapon", weight: 2, qty: 1, notes: "1d6 piercing, thrown 30/120" },
  { name: "Shortbow", category: "weapon", weight: 2, notes: "1d6 piercing, range 80/320" },
  { name: "Longbow", category: "weapon", weight: 2, notes: "1d8 piercing, range 150/600" },
  { name: "Light Crossbow", category: "weapon", weight: 5, notes: "1d8 piercing, range 80/320" },
  { name: "Heavy Crossbow", category: "weapon", weight: 18, notes: "1d10 piercing, range 100/400" },
  { name: "Sling", category: "weapon", weight: 0, notes: "1d4 bludgeoning, range 30/120" },
  { name: "Arrow", category: "weapon", weight: 0.05, qty: 20 },
  { name: "Crossbow Bolt", category: "weapon", weight: 0.075, qty: 20 },

  // ── Armor ──────────────────────────────────────────────────────────────
  { name: "Padded Armor", category: "armor", weight: 8, notes: "AC 11 + DEX; stealth disadvantage" },
  { name: "Leather Armor", category: "armor", weight: 10, notes: "AC 11 + DEX" },
  { name: "Studded Leather", category: "armor", weight: 13, notes: "AC 12 + DEX" },
  { name: "Hide Armor", category: "armor", weight: 12, notes: "AC 12 + DEX (max 2)" },
  { name: "Chain Shirt", category: "armor", weight: 20, notes: "AC 13 + DEX (max 2)" },
  { name: "Scale Mail", category: "armor", weight: 45, notes: "AC 14 + DEX (max 2); stealth disadvantage" },
  { name: "Breastplate", category: "armor", weight: 20, notes: "AC 14 + DEX (max 2)" },
  { name: "Half Plate", category: "armor", weight: 40, notes: "AC 15 + DEX (max 2); stealth disadvantage" },
  { name: "Ring Mail", category: "armor", weight: 40, notes: "AC 14; stealth disadvantage" },
  { name: "Chain Mail", category: "armor", weight: 55, notes: "AC 16, STR 13; stealth disadvantage" },
  { name: "Splint Armor", category: "armor", weight: 60, notes: "AC 17, STR 15; stealth disadvantage" },
  { name: "Plate Armor", category: "armor", weight: 65, notes: "AC 18, STR 15; stealth disadvantage" },
  { name: "Shield", category: "armor", weight: 6, notes: "+2 AC while equipped" },

  // ── Adventuring gear ───────────────────────────────────────────────────
  { name: "Rope (50 ft)", category: "gear", weight: 10 },
  { name: "Torch", category: "gear", weight: 1, qty: 5 },
  { name: "Hooded Lantern", category: "gear", weight: 2 },
  { name: "Flask of Oil", category: "gear", weight: 1, qty: 3 },
  { name: "Rations (1 day)", category: "gear", weight: 2, qty: 10 },
  { name: "Waterskin", category: "gear", weight: 5 },
  { name: "Bedroll", category: "gear", weight: 7 },
  { name: "Tent (two-person)", category: "gear", weight: 20 },
  { name: "Crowbar", category: "gear", weight: 5 },
  { name: "Grappling Hook", category: "gear", weight: 4 },
  { name: "Hammer", category: "gear", weight: 3 },
  { name: "Piton", category: "gear", weight: 0.25, qty: 10 },
  { name: "Caltrops", category: "gear", weight: 2, qty: 1 },
  { name: "Tinderbox", category: "gear", weight: 1 },
  { name: "Steel Mirror", category: "gear", weight: 0.5 },
  { name: "Signal Whistle", category: "gear", weight: 0 },
  { name: "Manacles", category: "gear", weight: 6 },
  { name: "Ink & Quill", category: "gear", weight: 0.1 },
  { name: "Scroll Case", category: "gear", weight: 1 },
  { name: "Backpack", category: "gear", weight: 5 },
  { name: "Belt Pouch", category: "gear", weight: 1 },
  { name: "Gold Coins", category: "gear", weight: 0.02, qty: 50 },

  // ── Tools & kits ───────────────────────────────────────────────────────
  { name: "Thieves' Tools", category: "tool", weight: 1, notes: "Pick locks and disarm traps" },
  { name: "Healer's Kit", category: "tool", weight: 3, notes: "Stabilize the dying; 10 uses" },
  { name: "Cartographer's Tools", category: "tool", weight: 6 },
  { name: "Disguise Kit", category: "tool", weight: 3 },
  { name: "Forgery Kit", category: "tool", weight: 5 },
  { name: "Herbalism Kit", category: "tool", weight: 3 },
  { name: "Navigator's Tools", category: "tool", weight: 2 },
  { name: "Poisoner's Kit", category: "tool", weight: 2 },
  { name: "Smith's Tools", category: "tool", weight: 8 },
  { name: "Alchemist's Supplies", category: "tool", weight: 8 },
  { name: "Cook's Utensils", category: "tool", weight: 8 },
  { name: "Musical Instrument (lute)", category: "tool", weight: 2 },

  // ── Potions & alchemy ──────────────────────────────────────────────────
  { name: "Potion of Healing", category: "potion", weight: 0.5, notes: "Restore 2d4+2 HP" },
  { name: "Potion of Greater Healing", category: "potion", weight: 0.5, notes: "Restore 4d4+4 HP" },
  { name: "Potion of Superior Healing", category: "potion", weight: 0.5, notes: "Restore 8d4+8 HP" },
  { name: "Antitoxin", category: "potion", weight: 0.5, notes: "Advantage vs poison for 1 hour" },
  { name: "Holy Water", category: "potion", weight: 0.5, notes: "2d6 radiant to fiends/undead" },
  { name: "Alchemist's Fire", category: "potion", weight: 1, notes: "1d4 fire, burns each turn" },
  { name: "Vial of Acid", category: "potion", weight: 1, notes: "2d6 acid on a direct hit" },

  // ── Magic items (flavor — mechanics pending) ───────────────────────────
  { name: "Cloak of Elvenkind", category: "magic", weight: 1, tags: ["magic"], notes: "Advantage on Stealth; observers have disadvantage to see you" },
  { name: "Boots of Stealth", category: "magic", weight: 1, tags: ["magic"], notes: "Silent footfalls" },
  { name: "Ring of Protection", category: "magic", weight: 0, tags: ["magic", "ac:+1"], notes: "+1 AC and saving throws" },
  { name: "Amulet of Health", category: "magic", weight: 0.05, tags: ["magic"], notes: "CON becomes 19" },
  { name: "Bag of Holding", category: "magic", weight: 15, tags: ["magic"], notes: "500 lb / 64 cu ft interior" },
  { name: "+1 Weapon (any)", category: "magic", weight: 3, tags: ["magic", "attack:+1"], notes: "Attacks with this weapon gain +1 to hit and damage" },

  // ── Additional weapons ────────────────────────────────────────────────
  { name: "Greatclub", category: "weapon", weight: 10, notes: "1d8 bludgeoning, two-handed" },
  { name: "Maul", category: "weapon", weight: 10, notes: "2d6 bludgeoning, heavy, two-handed" },
  { name: "Pike", category: "weapon", weight: 18, notes: "1d10 piercing, reach, two-handed" },
  { name: "Trident", category: "weapon", weight: 4, notes: "1d6 piercing, thrown 20/60" },
  { name: "Flail", category: "weapon", weight: 2, notes: "1d8 bludgeoning" },
  { name: "Lance", category: "weapon", weight: 6, notes: "1d12 piercing, reach, 2-handed on foot" },
  { name: "War Pick", category: "weapon", weight: 2, notes: "1d8 piercing" },
  { name: "Sickle", category: "weapon", weight: 2, notes: "1d4 slashing" },
  { name: "Scythe", category: "weapon", weight: 10, notes: "2d4 slashing, reach, heavy" },
  { name: "Blowgun", category: "weapon", weight: 1, notes: "1 piercing, range 25/100, uses darts" },
  { name: "Dart", category: "weapon", weight: 0.25, qty: 10, notes: "1d4 piercing, range 20/60" },
  { name: "Net", category: "weapon", weight: 3, notes: "Special: restrains target on a hit (DC 10)" },
  { name: "Yklwa", category: "weapon", weight: 3, notes: "1d8 piercing, thrown 10/30" },

  // ── Additional adventuring gear ───────────────────────────────────────
  { name: "10-foot Pole", category: "gear", weight: 8 },
  { name: "Ball Bearings", category: "gear", weight: 2, qty: 1000, notes: "Covers 10 ft; Difficult Terrain" },
  { name: "Block and Tackle", category: "gear", weight: 5 },
  { name: "Bell", category: "gear", weight: 0 },
  { name: "Candle", category: "gear", weight: 0, qty: 10, notes: "Burns 1 hour" },
  { name: "Chain (10 ft)", category: "gear", weight: 2 },
  { name: "Chalk (1 piece)", category: "gear", weight: 0 },
  { name: "Chest", category: "gear", weight: 25 },
  { name: "Climber's Kit", category: "gear", weight: 12 },
  { name: "Fishing Tackle", category: "gear", weight: 4 },
  { name: "Hunting Trap", category: "gear", weight: 25, notes: "DC 13 to escape; 1d4 piercing" },
  { name: "Magnifying Glass", category: "gear", weight: 0 },
  { name: "Poison (Basic)", category: "gear", weight: 2, notes: "DC 10 Con or 1d4 poison" },
  { name: "Scale", category: "gear", weight: 3 },
  { name: "Sealing Wax", category: "gear", weight: 0 },
  { name: "Shovel", category: "gear", weight: 5 },
  { name: "Soap", category: "gear", weight: 0 },
  { name: "Spike (Iron)", category: "gear", weight: 5, qty: 10 },
  { name: "Spyglass", category: "gear", weight: 1 },
  { name: "Whetstone", category: "gear", weight: 1 },
  { name: "Blanket", category: "gear", weight: 3 },
  { name: "Book", category: "gear", weight: 5 },
  { name: "Abacus", category: "gear", weight: 2 },
  { name: "Antitoxin Vial", category: "gear", weight: 0.5 },

  // ── Additional tools & kits ───────────────────────────────────────────
  { name: "Carpenter's Tools", category: "tool", weight: 6 },
  { name: "Cobbler's Tools", category: "tool", weight: 5 },
  { name: "Glassblower's Tools", category: "tool", weight: 12 },
  { name: "Jeweler's Tools", category: "tool", weight: 2 },
  { name: "Leatherworker's Tools", category: "tool", weight: 5 },
  { name: "Mason's Tools", category: "tool", weight: 8 },
  { name: "Painter's Supplies", category: "tool", weight: 5 },
  { name: "Potter's Tools", category: "tool", weight: 3 },
  { name: "Tinker's Tools", category: "tool", weight: 10 },
  { name: "Weaver's Tools", category: "tool", weight: 5 },
  { name: "Woodcarver's Tools", category: "tool", weight: 5 },
  { name: "Vehicles: Cart", category: "tool", weight: 200, notes: "Carries 1,000 lb" },
  { name: "Vehicles: Wagon", category: "tool", weight: 400, notes: "Carries 2,000 lb" },
  { name: "Vehicles: Rowboat", category: "tool", weight: 100, notes: "Carries 4 people" },
  { name: "Vehicles: Sailing Ship", category: "tool", weight: 100000, notes: "Carries 100 tons" },

  // ── Additional potions & alchemy ──────────────────────────────────────
  { name: "Potion of Climbing", category: "potion", weight: 0.5, notes: "Climb speed = 10 ft, advantage on climbs" },
  { name: "Potion of Water Breathing", category: "potion", weight: 0.5, notes: "Breathe water for 1 hour" },
  { name: "Potion of Fire Resistance", category: "potion", weight: 0.5, notes: "Resistance to fire for 1 hour" },
  { name: "Potion of Heroism", category: "potion", weight: 0.5, notes: "Temp HP + advantage on saves" },
  { name: "Potion of Invisibility", category: "potion", weight: 0.5, notes: "Invisible until attack" },
  { name: "Potion of Giant Strength (Hill)", category: "potion", weight: 0.5, notes: "STR set to 21 for 1 hour" },
  { name: "Potion of Giant Strength (Frost)", category: "potion", weight: 0.5, notes: "STR set to 23 for 1 hour" },
  { name: "Elixir of Health", category: "potion", weight: 0.5, notes: "Cures diseases and conditions" },
  { name: "Oil of Slipperiness", category: "potion", weight: 0.5, notes: "Coats surface; escape grapple as a bonus action" },
  { name: "Philter of Love", category: "potion", weight: 0.5, notes: "Charmed by next creature met" },

  // ── Additional magic items (flavor — mechanics pending) ───────────────
  { name: "Wand of Magic Missiles", category: "magic", weight: 1, tags: ["magic"], notes: "1 charge: 1d4+1 force darts; recharges daily" },
  { name: "Wand of Fireballs", category: "magic", weight: 1, tags: ["magic"], notes: "7 charges: 8d6 fire in 20-ft radius" },
  { name: "Staff of Power", category: "magic", weight: 4, tags: ["magic"], notes: "+2 attack/damage, 20 charges of spells" },
  { name: "Staff of the Magi", category: "magic", weight: 4, tags: ["magic"], notes: "+2, 50 charges, absorbs spells" },
  { name: "Flame Tongue", category: "magic", weight: 4, tags: ["magic", "attack:+2"], notes: "Greatsword: +2, +2d6 fire while lit" },
  { name: "Frost Brand", category: "magic", weight: 3, tags: ["magic", "attack:+1"], notes: "Sword: +1, +1d6 cold, resists fire" },
  { name: "Vorpal Sword", category: "magic", weight: 3, tags: ["magic", "attack:+3"], notes: "Longsword: +3, beheads on a 20" },
  { name: "Hammer of Thunderbolts", category: "magic", weight: 10, tags: ["magic", "attack:+1"], notes: "Maul: +1, thunderous banish on a 20" },
  { name: "Sword of Sharpness", category: "magic", weight: 3, tags: ["magic", "attack:+1"], notes: "Greatsword: +1, extra 14 slashing on a 20" },
  { name: "Belt of Giant Strength (Stone)", category: "magic", weight: 1, tags: ["magic"], notes: "STR becomes 23" },
  { name: "Boots of Speed", category: "magic", weight: 1, tags: ["magic"], notes: "Doubles speed as a bonus action" },
  { name: "Bracers of Defense", category: "magic", weight: 1, tags: ["magic", "ac:+2"], notes: "+2 AC when not wearing armor" },
  { name: "Cloak of Protection", category: "magic", weight: 1, tags: ["magic", "ac:+1"], notes: "+1 AC and saving throws" },
  { name: "Gauntlets of Ogre Power", category: "magic", weight: 2, tags: ["magic"], notes: "STR becomes 19" },
  { name: "Helm of Brilliance", category: "magic", weight: 3, tags: ["magic"], notes: "Resistance to fire; flames on command" },
  { name: "Ioun Stone (Protection)", category: "magic", weight: 0, tags: ["magic", "ac:+1"], notes: "+1 AC" },
  { name: "Pearl of Power", category: "magic", weight: 0, tags: ["magic"], notes: "Regain a spent spell slot" },
  { name: "Ring of Spell Storing", category: "magic", weight: 0, tags: ["magic"], notes: "Hold up to 5 levels of spells" },
  { name: "Rod of Lordly Might", category: "magic", weight: 5, tags: ["magic"], notes: "Many modes: mace, lance, ladder, etc." },
  { name: "Scarab of Protection", category: "magic", weight: 1, tags: ["magic"], notes: "Resistance to necrotic, wards undead" },
  { name: "Stone of Good Luck", category: "magic", weight: 1, tags: ["magic"], notes: "+1 to all ability checks/saves" },
  { name: "Deck of Many Things", category: "magic", weight: 1, tags: ["magic"], notes: "Draw cards — fortune or ruin" },
  { name: "Bag of Tricks (Gray)", category: "magic", weight: 1, tags: ["magic"], notes: "Pull a random beast ally" },
  { name: "Figurine of Wondrous Power", category: "magic", weight: 1, tags: ["magic"], notes: "Becomes a living beast for 6 hours" },

  // ── Class kit (every class starting_item is catalogued) ───────────────
  { name: "Holy Symbol", category: "gear", weight: 0.1, notes: "Divine channeling focus" },
  { name: "Spellbook", category: "gear", weight: 3, notes: "Wizard's prepared spells" },
  { name: "Arcane Focus", category: "gear", weight: 0.5 },
  { name: "Robes", category: "gear", weight: 4 },
  { name: "Adventurer's Clothes", category: "gear", weight: 4 },
  { name: "Grimoire of the Patron", category: "gear", weight: 3, notes: "Terms subject to change" },
  { name: "Lute", category: "tool", weight: 2 },
  { name: "Wooden Shield", category: "armor", weight: 6, notes: "+2 AC while equipped" },
  { name: "Druidic Focus", category: "gear", weight: 0.5 },
  { name: "War Banner", category: "gear", weight: 2, notes: "Rally point for allies" },
  { name: "Feathered Hat", category: "gear", weight: 0.5 },
  { name: "Rune Chisel", category: "tool", weight: 0.5 },
  { name: "Bone Focus", category: "gear", weight: 0.5 },
  { name: "Grave Dirt Satchel", category: "gear", weight: 2 },
  { name: "Spirit Totem", category: "gear", weight: 1 },
  { name: "Crystal Focus", category: "gear", weight: 0.2 },
  { name: "Simple Robes", category: "gear", weight: 3 },
  { name: "Journal of Dreams", category: "gear", weight: 2 },
  { name: "Acid Flask", category: "potion", weight: 1, notes: "2d6 acid on a direct hit" },
  { name: "Leather Apron", category: "armor", weight: 3 },
  { name: "Clockwork Scarab", category: "magic", weight: 1, tags: ["magic"], notes: "Wind-up crawler; scouts and unlocks" },
  { name: "Oil Can", category: "tool", weight: 0.5 },
  { name: "Trophy Chain", category: "gear", weight: 2 },
  { name: "Brass Knuckles", category: "weapon", weight: 0.5, notes: "Unarmed strikes deal 1d4" },
  { name: "Padded Vest", category: "armor", weight: 8, notes: "AC 11 + DEX" },
  { name: "Waterskin (Ale)", category: "gear", weight: 5 },
  { name: "Animal Whistle", category: "tool", weight: 0.05 },
  { name: "Dark Cloak", category: "gear", weight: 2 },
  { name: "Storm Talisman", category: "magic", weight: 0.3, tags: ["magic"], notes: "Hums before lightning strikes" },
  { name: "Lightning-Scarred Shield", category: "armor", weight: 6, notes: "+2 AC; static charge lingers" },
  { name: "Broomstick (well-used)", category: "magic", weight: 3, tags: ["magic"], notes: "Allegedly flies. Mostly sweeps." },
  { name: "Herb Pouch", category: "gear", weight: 2 },
  { name: "Black Cat Familiar", category: "magic", weight: 0, tags: ["magic"] },
  { name: "Summoning Circle Chalk", category: "gear", weight: 0.2 },
  { name: "Contract Ledger", category: "gear", weight: 2 },
  { name: "Heavy Crossbow (hand-cannon)", category: "weapon", weight: 18, notes: "Loud in every sense" },
  { name: "Powder Horn", category: "tool", weight: 1 },
  { name: "Leather Duster", category: "armor", weight: 4 },
  { name: "Longspear", category: "weapon", weight: 6, notes: "1d8 piercing, reach" },
  { name: "Dragon-Tooth Charm", category: "magic", weight: 0.2, tags: ["magic"], notes: "Wyrms hesitate, briefly" },
  { name: "Blackened Plate", category: "armor", weight: 65, notes: "AC 18; smells faintly of brimstone" },
  { name: "Cracked Holy Symbol", category: "gear", weight: 0.1 },
  { name: "Silvered Mace", category: "weapon", weight: 4, notes: "1d6 bludgeoning; silvered" },
  { name: "Salt Circle Kit", category: "tool", weight: 3 },
  { name: "Scripture Ribbons", category: "gear", weight: 0.3 },
  { name: "Slapstick (hidden blade)", category: "weapon", weight: 1, notes: "Comedy first. Blade second." },
  { name: "Motley", category: "gear", weight: 2 },
  { name: "Juggling Daggers", category: "weapon", weight: 1, qty: 3 },
  { name: "Whetstone of Focusing", category: "magic", weight: 0.3, tags: ["magic"] },
  { name: "Chirurgeon's Kit", category: "tool", weight: 4, notes: "Sutures, saws, speculation" },
  { name: "Bandages & Sutures", category: "gear", weight: 1 },
  { name: "Specimen Jar", category: "gear", weight: 1 },
  { name: "Four-Chambered Orb", category: "magic", weight: 0.5, tags: ["magic"] },
  { name: "Fireproof Gloves", category: "magic", weight: 0.5, tags: ["magic"] },
  { name: "Traveling Robes", category: "gear", weight: 4 },
  { name: "Warhorse", category: "gear", weight: 0, notes: "Mount — stabled separately" },
];

export function findEquipment(name: string): EquipmentEntry | undefined {
  const needle = name.trim().toLowerCase();
  return EQUIPMENT_CATALOG.find((e) => e.name.toLowerCase() === needle);
}
